Add coffee build output for non-coffee module users
resin-io/dockerfile-template pull request #2
Opened 2017-02-28 13:37 UTC by CameronDiver

Change-type: minor
Connects-to: #1
Signed-off-by: Cameron Diver <cameron@resin.io>

2017-03-01 11:38 UTC, hedss requested changes
What we usually do for modules written in CoffeeScript that need to be general accessible is to build them with `gulp`, with appropriate instructions in the `package.json` for prepublishing/build/test instructions.

That way you can have the `main: lib.js` property set and know that you don't have to do everything yourself (esp. with prepublish).

Here's a couple of repos that use `gulp`:
https://github.com/resin-io/resin-cli
https://github.com/resin-io-modules/resin-discoverable-services

And here's a link to the NPM page describing `prepublish` and building for other languages (handily it includes CS!):
https://docs.npmjs.com/files/package.json

2017-03-01 14:22 UTC, hedss approved these changes
LGTM!

2017-03-01 14:45 UTC, merged

2017-03-03 02:09 UTC, Page- commented on package.json
> +    "pretest": "coffeelint lib.coffee dockerfile-template.coffee ./test",
Can you switch to resin-lint please :)

2017-03-03 02:09 UTC, Page- commented on package.json
> +    "prepublish": "gulp && (echo '#!/usr/bin/env node' | cat - dockerfile-template.js > dockerfile-template)"
This should use the [`bin`](https://docs.npmjs.com/files/package.json#bin) property of package.json in order to make the script executable - it handles the execute permission bit on linux, and also generates a .cmd for windows